### ISSUE TITLE
live.novaramedia.com currently crashes chrome on OSX 10.10.4

### ISSUE THREAD

**Issue by Gaffen** [novaramedia/live-novaramedia-com#1]
![screen shot 2015-08-07 at 17 00 22](https://cloud.githubusercontent.com/assets/718125/9140005/d65dad48-3d25-11e5-89ec-7af11bced920.png)

Chrome version:
**44.0.2403.130**

live.novaramedia.com completes the initial http request, however the browser window crashes before the javascript can initialise.

I will attempt to clone this repo and identify the cause later, if needed.

All the best,

-Gaffen

**Comment by varffs** [comment]
Strange, same versions of everything and works fine for me. But that is when the show is offline. Perhaps the jPlayer in the streaming bit is doing something strange. 

It is actually pretty out of date as a rebuild and retheme is in the works. Perhaps this bug is more of a bump for that work

**Comment by Gaffen** [comment]
Closing issue as bug doesn't persist to develop branch
